apiVersion: v1
kind: Pod
metadata:
  namespace: test
  name: app2
  labels:
    name: app2
spec:
  containers:
  - name: app2
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
