apiVersion: v1 # its for template for schema
kind: Pod # tells kubernetes what to create
metadata: # details about pod
  name: nginx
  labels:
    name: myPod
    type: proxy
spec: # this tells what to create
  containers:
  - name: nginx-container # name we want to give the container inside the pod
    image: nginx:latest # docker image that should be used, will pull from dockerhub in case of missing locally
    resources:
      limits:
        memory: "128Mi" # measured in bytes (1024 = 1Ki but 1000 = 1k)
        cpu: "500m" # measured in cpu units 1=1 CPU/virtual core, 
    ports:
      - containerPort: 80
