# deployment that have 2 pods running 2 containers in each pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mydeployment
  labels:
    name:  mydeployment
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1 # max number of pods that can be scheduled above desired number of pods
      maxUnavailable: 1 # max number of pods that can be unavailable during update
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginxcontainer
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
      - name: ubuntucontainer
        image: ubuntu
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        command: [ "/bin/bash", "-c"] # will be executed when container starts
        args:
          - sleep 300 # sleep is keeping container busy, when it finish its job it will close