# deployment that runs hello-world container before nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mydeployment
  labels:
    name:  mydeployment
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers: # init containers run before other containers and are usefull for one time jobs like downloading certificates
      - name: initcontainer
        image: hello-world
      containers:
      - name: nginxcontainer
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80