apiVersion: apps/v1
kind: Deployment
metadata:
  name:  stress-deploy
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: php-app
        image: k8s.gcr.io/hpa-example # there is app which starts count to infinity everytime its queried
        resources:
          limits:
            memory: "250Mi"
            cpu: "250m"
        ports:
          - containerPort: 80
        imagePullPolicy: Always
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pod-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stress-deploy
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
# service for Pod to Pod communication
kind: Service
apiVersion: v1
metadata:
  name: php-service
spec:
  selector:
    app: stress
  type: ClusterIP
  ports:
  - port:  80
    targetPort:  80

# To run stress test create another pod and querry php app:
# kubectl run stressor --image=busybox --command -- sleep 500
# kubectl exec -it stressor -- /bin/sh
# while true; do wget -q -O- http://php-service.default.svc.cluster.local; done